[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "data-validation-engine"
version = "2.0.0"
description = "Automated Data Validation & Cleaning Engine"
dependencies = [
    "pandas",
    "streamlit",
    "plotly",
    "openpyxl"
]
